# shinobi-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinobi-db-pvc
  namespace: shinobi-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinobi-data-pvc
  namespace: shinobi-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
